services:
  - type: web
    name: woodkala-nepal
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Wood Kala Nepal
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://woodkala-nepal.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: woodkala-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_LEVEL
        value: error

databases:
  - name: woodkala-db
    databaseName: woodkala
    user: woodkala
